//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMK_24_3_client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        double[] GetData(float r, float k, float b, float delta, float rectSquare, float square, System.Drawing.Point C, System.Drawing.Point D, int iterations);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<double[]> GetDataAsync(float r, float k, float b, float delta, float rectSquare, float square, System.Drawing.Point C, System.Drawing.Point D, int iterations);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRealSquare", ReplyAction="http://tempuri.org/IService1/GetRealSquareResponse")]
        float GetRealSquare(System.Drawing.Point C, System.Drawing.Point D);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRealSquare", ReplyAction="http://tempuri.org/IService1/GetRealSquareResponse")]
        System.Threading.Tasks.Task<float> GetRealSquareAsync(System.Drawing.Point C, System.Drawing.Point D);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSomeData", ReplyAction="http://tempuri.org/IService1/GetSomeDataResponse")]
        float[] GetSomeData(System.Drawing.Point C, System.Drawing.Point D);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSomeData", ReplyAction="http://tempuri.org/IService1/GetSomeDataResponse")]
        System.Threading.Tasks.Task<float[]> GetSomeDataAsync(System.Drawing.Point C, System.Drawing.Point D);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : MMK_24_3_client.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<MMK_24_3_client.ServiceReference1.IService1>, MMK_24_3_client.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double[] GetData(float r, float k, float b, float delta, float rectSquare, float square, System.Drawing.Point C, System.Drawing.Point D, int iterations) {
            return base.Channel.GetData(r, k, b, delta, rectSquare, square, C, D, iterations);
        }
        
        public System.Threading.Tasks.Task<double[]> GetDataAsync(float r, float k, float b, float delta, float rectSquare, float square, System.Drawing.Point C, System.Drawing.Point D, int iterations) {
            return base.Channel.GetDataAsync(r, k, b, delta, rectSquare, square, C, D, iterations);
        }
        
        public float GetRealSquare(System.Drawing.Point C, System.Drawing.Point D) {
            return base.Channel.GetRealSquare(C, D);
        }
        
        public System.Threading.Tasks.Task<float> GetRealSquareAsync(System.Drawing.Point C, System.Drawing.Point D) {
            return base.Channel.GetRealSquareAsync(C, D);
        }
        
        public float[] GetSomeData(System.Drawing.Point C, System.Drawing.Point D) {
            return base.Channel.GetSomeData(C, D);
        }
        
        public System.Threading.Tasks.Task<float[]> GetSomeDataAsync(System.Drawing.Point C, System.Drawing.Point D) {
            return base.Channel.GetSomeDataAsync(C, D);
        }
    }
}
